/**
 * @file Hardcoded Databases for development and demo purposes.
 */

/**
 * Database object containing the list of users
 * @typedef {object} UsersDatabaseObject
 * @typedef {object} UniqueUserObject
 *
 * @property {UniqueUserObject}                 - unique id as object-key generated by generateRandomString
 * @property {string} UniqueUserObject.id       - unique id generated by generateRandomString()
 * @property {string} UniqueUserObject.email    - user's email.
 * @property {string} UniqueUserObject.password - user's password
 */
const users = {
  userRandomID: {
    id: "userRandomID",
    email: "user@example.com",
    password: "purple-monkey-dinosaur",
  },
  user2RandomID: {
    id: "user2RandomID",
    email: "user2@example.com",
    password: "dishwasher-funk",
  },
  aJ48lW: {
    id: "aJ48lW",
    email: "user@email.com",
    password: "pass",
  },
};

/**
 * Database object containing the list of URLS
 * @typedef {object} UrlssDatabaseObject
 * @typedef {object} UniqueURLObject
 *
 * @property {UniqueURLObject}                - (ShortURL) unique id as object-key generated by generateRandomString
 * @property {string} UniqueURLObject.longURL - Long form of Target URL.
 * @property {string} UniqueURLObject.userID  - URL user owner
 */
const urlDatabase = {
  b2xVn2: {
    longURL: "http://www.lighthouselabs.ca",
    userID: "userRandomID",
  },
  "9sm5xK": {
    longURL: "http://www.google.com",
    userID: "user2RandomID",
  },
  b6UTxQ: {
    longURL: "https://www.tsn.ca",
    userID: "aJ48lW",
  },
  i3BoGr: {
    longURL: "https://www.google.ca",
    userID: "aJ48lW",
  },
};

module.exports = {
  users,
  urlDatabase
};