/**
 * @file Hardcoded Databases for development and demo purposes.
 */

/**
 * Database object conatining the list of users
 * @typedef {object} UsersDatabaseObject
 * @typedef {object} UniqueUserObject
 *
 * @property {UniqueUserObject}                 - unique id as object-key generated by generateRandomString
 * @property {string} UniqueUserObject.id       - unique id generated by generateRandomString()
 * @property {string} UniqueUserObject.email    - user's email.
 * @property {string} UniqueUserObject.password - user's password
 */
const users = {
  userRandomID: {
    id: "userRandomID",
    email: "user@example.com",
    password: "purple-monkey-dinosaur",
  },
  user2RandomID: {
    id: "user2RandomID",
    email: "user2@example.com",
    password: "dishwasher-funk",
  },
  aJ48lW: {
    id: "aJ48lW",
    email: "user@email.com",
    password: "pass",
  },
};



module.exports = {
  users,

};